export { default as Dashboard } from './Dashboard'
export { default as MyCourses } from './MyCourses'
export { default as CourseDetails } from './CourseDetails'
export { default as Blogs } from './Blogs'
export { default as Products } from './Products'
export { default as Profile } from './Profile'